//
// Created by beiying on 2020/9/13.
//

#define DELETE(obj) if(obj) {delete obj;obj = 0;}

#ifndef LOPNOR_MACRO_H
#define LOPNOR_MACRO_H
#define THREAD_MAIN 1
#define THREAD_CHILD 2
#define FFMPEG_CAN_NOT_OPEN_URL 1
#define FFMPEG_CAN_NOT_FIND_STREAMS 2
#define FFMPEG_FIND_DECODER_FAIL 3
#define FFMPEG_ALLOC_CODEC_CONTEXT_FAIL 4
#define FFMPEG_CODEC_CONTEXT_PARAMETERS_FAIL 6
#define FFMPEG_OPEN_DECODER_FAIL 7
#define FFMPEG_NOMEDIA 8
#endif //LOPNOR_MACRO_H
